service: books

frameworkVersion: ">=1.28.0 <2.0.0"

provider:
  name: aws
  runtime: go1.x
  timeout: 120
  environment:
    DB_USER: ${file(./serverless.env.yml):DB_USER}
    DB_PSWD: ${file(./serverless.env.yml):DB_PSWD}
    DB_NAME: ${file(./serverless.env.yml):DB_NAME}
    DB_HOST: ${file(./serverless.env.yml):DB_HOST}

package:
 exclude:
   - ./**
 include:
   - ./bin/**

functions:
  create:
    handler: bin/create
    events:
      - http:
          path: book
          method: post
  search:
    handler: bin/search
    events:
      - http:
          path: book/{id}
          method: get
  scrap:
    handler: bin/scrap
    events:
      - http:
          path: books
          method: get
